/** Momentum System: a bottleneck-first booking route that preserves the Calendar workflow while reducing uncertainty with outcome-led copy. */
import { ArrowRight, CalendarDays, MessageSquareText, Route } from "lucide-react";
import { BookingBenefits, BookingCallout } from "@/components/BookingWorkflow";
import { PageLayout } from "@/components/PageLayout";

export default function Book() {
  return <PageLayout>
    <section className="booking-page-hero"><div className="content-frame booking-page-hero__grid"><div><span className="section-kicker"><span className="pulse-dot" /> A focused growth systems call</span><h1>Find the bottleneck holding your business back.</h1><p>Bring the process, customer journey, or manual task that is slowing you down. In 30 minutes, we will help you identify one practical system to improve next.</p><BookingCallout label="Find my biggest bottleneck" /><BookingBenefits /></div><aside className="booking-page-hero__side"><span>What happens next</span><ol><li><strong>01</strong> Tell us where the business is getting stuck.</li><li><strong>02</strong> Choose a time through the secure calendar.</li><li><strong>03</strong> Leave with a clearer practical next step.</li></ol></aside></div></section>
    <section className="booking-expectations content-frame"><div><span className="eyebrow">Useful by default</span><h2>Bring the real question, not a polished pitch.</h2><p>We use the session to understand your business in context. It may be a new idea, a site that is not doing enough work, a WhatsApp-led customer journey that loses momentum, a clumsy manual process, or simply uncertainty about where to focus.</p></div><div className="expectation-list"><span><MessageSquareText size={22} /><strong>A practical conversation</strong><small>No generic presentation or overcomplicated tech talk.</small></span><span><Route size={22} /><strong>A clearer direction</strong><small>We will identify the decision, system, or first step worth prioritising.</small></span><span><CalendarDays size={22} /><strong>A low-risk next step</strong><small>No obligation. You will leave with one practical improvement to consider.</small></span></div></section>
    <section className="booking-final"><div className="booking-final__inner"><div className="booking-final__copy"><span className="eyebrow eyebrow--lime">03 / calendar endpoint</span><h2>Choose a time that works for you.</h2><p>It takes a minute to provide context, then the calendar will show live availability.</p><BookingCallout label="Start a conversation" /><a href="https://calendly.com/serveiqafrica/30min" target="_blank" rel="noreferrer" className="text-link">Prefer a new browser window? Open Calendly directly <ArrowRight size={15} /></a></div><aside className="booking-final__system"><span className="system-status"><i /> Session system / active</span><div><strong>30 min</strong><span>Focused working time</span></div><div><strong>01 → 03</strong><span>Context, calendar, conversation</span></div></aside></div></section>
  </PageLayout>;
}
