/** Momentum System: learning-lab page that presents a credible ecosystem without inventing products, reviews, or outcomes. */
import { ArrowRight, BookOpenCheck, Lightbulb, UsersRound } from "lucide-react";
import { BookingCallout } from "@/components/BookingWorkflow";
import { PageLayout } from "@/components/PageLayout";

const ORBIT_URL = "/manus-storage/launchrlabs-africa-orbit_5adf44de.jpg";

export default function Resources() {
  return <PageLayout>
    <section className="page-hero page-hero--resources"><div className="content-frame page-hero__grid"><div><span className="section-kicker"><span className="pulse-dot" /> The learning lab</span><h1>Useful knowledge for people who are building in public.</h1></div><p>LaunchrLabs is growing an accessible library of practical education, tools, and shared learning for African internet businesses.</p></div></section>
    <section className="resource-intro content-frame"><div className="resource-intro__copy"><span className="eyebrow">The purpose</span><h2>Make modern digital business knowledge easier to use.</h2><p>The learning lab is where our launch philosophy becomes useful beyond a single project: clear guidance, practical workshops, and community-led spaces for better questions.</p></div><div className="resource-intro__visual"><img src={ORBIT_URL} alt="Abstract orbit structure representing a connected learning ecosystem" /><span className="image-signal"><i /> Learning loop / open</span></div></section>
    <section className="resource-grid content-frame"><article><BookOpenCheck size={28} strokeWidth={1.5} /><span className="eyebrow">Guides & playbooks</span><h3>Clear starting points for the work that matters.</h3><p>Launch guides, practical AI use cases, website decision frameworks, and systems thinking that skips the jargon.</p></article><article><Lightbulb size={28} strokeWidth={1.5} /><span className="eyebrow">Workshops & field sessions</span><h3>Build capability while you build the business.</h3><p>Focused learning experiences for founders and teams who want to understand the systems behind their growth.</p></article><article><UsersRound size={28} strokeWidth={1.5} /><span className="eyebrow">Community</span><h3>Better momentum is easier with peers.</h3><p>A future-facing space for founders, creators, and operators to share experiments, lessons, and useful connections.</p></article></section>
    <section className="resource-note"><div className="content-frame resource-note__grid"><div><span className="eyebrow eyebrow--lime">In development</span><h2>Tools, templates, and learning programmes are taking shape.</h2></div><div><p>Want to hear about the next workshop or resource drop? Bring your current question to a working session and we will point you toward the most relevant next step.</p><BookingCallout /><a href="mailto:hello@launchrlabs.africa?subject=Learning%20Lab%20updates" className="text-link">Ask about the learning lab <ArrowRight size={15} /></a></div></div></section>
  </PageLayout>;
}
